_schema: _schema
paths:
  uploads:
  uploads_use_relative_path: true
  static: ''
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: content/posts
    glob:
      - '**/*.{svg,webp,png,jpg,jpeg,md}'
    name: Posts
    singular_name:
    icon: event_available
    disable_url: false
    description: ''
    preview:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
        create:
          path: '[relative_base_path]/{title|slugify}/index.md'
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
        _inputs:
          title:
timezone: Australia/Melbourne
markdown:
  engine: commonmark
  options:
    html: true
